### ISSUE TITLE
handle migrations in one folder and Run migrations independent from API server 

### ISSUE THREAD

**Issue by muhammad-asghar-ali** [0xbase-Corp/portfolio_svc#19]
check this [Golang Database Migrations](https://www.freecodecamp.org/news/database-migration-golang-migrate/#:~:text=Create%20a%20directory%20like%20database,store%20all%20the%20migration%20files.&text=You%20use%20%2Dseq%20to%20generate,the%20name%20of%20the%20migration.)

**Comment by muhammad-asghar-ali** [comment]
Getting the error when start the go server due to not found migration in folder 
<img width="778" alt="image" src="https://github.com/0xbase-Corp/portfolio_svc/assets/51094535/2d555cf7-6ca8-40cc-bf64-c9d7b71af97f">

**Comment by 0xmzz** [comment]
hey so we run this in docker, so it will work otherwise you will need to adjust the path in migrations.go as it is old.

**Comment by muhammad-asghar-ali** [comment]
the best practice  for migration is put all the migrations in one folder because when we up the migrations it run in sequence e.g. 001, 002 and so on.

**Comment by ibilalkayy** [comment]
I am trying to run the docker image but it is taking way much time than expected.

**Comment by fuddin95** [comment]
@ibilalkayy the first time is the longest, the subsequent times is faster
